image_dim: [960, 1280]
coord_output: true
mask_output: true
glyph_coord_output: true
glyph_mask_output: true

vertical: true
quality: [50, 95]
visibility_check: true

midground: 0.
midground_offset:
  percents: [[-0.5, 0.5], [-0.5, 0.5]]
foreground_mask_pad: 6

corpus:
  weights: [1]
  args:
    #length augmentable corpus
    - paths: [resources/corpus/vertical.txt]
      weights: [1]
      min_length: 1
      max_length: 10
      # textcase: [lower]
      augmentation: 0.
      augmentation_length: [1, 10]

font:
  paths: [resources/font2]
  weights: [1]
  size: [24, 54]
  bold: 0.01

texture:
  prob: 1.
  args:
    paths: [resources/image]
    weights: [1]
    alpha: [0, 1]
    grayscale: 0
    crop: 0.3

colormap2:
  paths: [resources/colormap/colormap3.txt]
  weights: [1]
  k: 2
  alpha: [1, 1]
  colorize: 1

colormap3:
  paths: [resources/colormap/colormap3.txt]
  weights: [1]
  k: 3
  alpha: [1, 1]
  colorize: 1

color:
  gray: [0, 255]
  alpha: [1, 1]
  colorize: 1

text_color:
  prob: 0.3
  args:
    weights: [1, 1]
    args:
      - rgb: [[180,255], [0,40], [0,40]]
        alpha: [1,1]
        grayscale: 0

      - rgb: [[0,40], [0,20], [0,20]]
        alpha: [1,1]
        grayscale: 0

background_color:
  rgb: [[180,255], [180,255], [180,255]]
  alpha: [1,1]
  grayscale: 0

shape:
  prob: 0.1
  args:
    weights: [1, 0]
    args:
      # elastic distortion
      - alpha: [15, 30]
        sigma: [4, 12]
      # elastic distortion
      - alpha: [0, 2]
        sigma: [0, 0.6]

layout:
  weights: [1, 0]
  args:
    # flow layout
    - space: [-16, -7]
      line_align: [middle]
    # curve layout
    - curve: [20, 40]
      space: [-2, 5]
      convex: 0.5
      upward: 0.5

style:
  prob: 0.1
  args:
    weights: [1, 1, 0]
    args:
      # text border
      - size: [1, 12]
        alpha: [1, 1]
        grayscale: 0
      # text shadow
      - distance: [1, 2]
        angle: [0, 360]
        alpha: [0.3, 0.7]
        grayscale: 0
      # text extrusion
      - length: [1, 12]
        angle: [0, 360]
        alpha: [1, 1]
        grayscale: 0

char_transform:
  # crop
  prob: 0.4
  args:
    percents: [[0.5, 0.8],[1,1]]
    direction: left

transform:
  args:
  # crop
    # - prob: 0.4
    #   args:
    #     percents: [[0.5, 0.8],[1,1]]
    # perspective
    - prob: 0.5
      args:
        percents: [[0.7, 0.9], [1., 1.]]
        aligns: [[0, 0], [0, 0]]
    # perspective
    - prob: 0.2
      args:
        percents: [[1, 1], [0.7, 0.9]]
        aligns: [[0, 0], [0, 0]]
    # rotation
    - prob: 1
      args:
        angle: [1, 120]
        ccw: 0.5
    # trapezoidate y
    - prob: 0.3
      args:
        weights: [1, 0, 0,0]
        percent: [0.4, 1]
        align: [-1, 1]
    # SKEW
    - prob: 0.2
      args:
        weights: [1, 0]
        angle: [10, 30]
        ccw: 0.5
    - prob: 0.2
      args:
        weights: [0, 1]
        angle: [10, 30]
        ccw: 0.5

# size_transform:
#   args:
#     weights: [0,0,1,0]
#     args: 
#       - percents: [[0.4, 0.6], [0.4, 0.8]]
#         aligns: [[0, 0], [0, 0]]
#       - percents: [[0.4, 0.8], [0.4, 0.6]]
#         aligns: [[0, 0], [0, 0]]
#       - percents: [[0.4, 0.6], [0.4, 0.6]]
#         aligns: [[0, 0], [0, 0]]
#       - percents: [[0.3, 1], [0.3, 1]]
#         aligns: [[0, 0], [0, 0]]

pad:
  prob: 0.
  args:
    pxs: [[3, 15], [3, 15], [3, 15], [3, 15]]

postprocess:
  args:
    # gaussian noise
    - prob: 0.
      args:
        scale: [1, 5]
        per_channel: 0
    # gaussian blur
    - prob: 0.
      args:
        sigma: [0.1, 2]
    # resample
    - prob: 0.
      args:
        size: [0.4, 0.4]
    # median blur
    - prob: 0.
      args:
        k: [1, 3]
