image_dim: [32, 32]
coord_output: true
mask_output: true
glyph_coord_output: true
glyph_mask_output: true

vertical: true
quality: [50, 95]
visibility_check: true

midground: 1.
midground_offset:
  percents: [[-0.5, 0.5], [-0.5, 0.5]]
foreground_mask_pad: 1

corpus:
  weights: [1, 0]
  args:
    #length augmentable corpus
    - paths: [resources/corpus/character2.txt, resources/corpus/character.txt, resources/corpus/suit.txt, resources/corpus/suit2.txt]
      weights: [1,1,1,1]
      min_length: 1
      max_length: 1
      # textcase: [lower]
      augmentation: 0.
      augmentation_length: [1,15]
    # char augmentable corpus
    - paths: []
      weights: []
      min_length: 1
      max_length: 25
      textcase: [lower, upper, capitalize]
      augmentation: 0
      augmentation_charset: resources/charset/test.txt

font:
  paths: [resources/font2]
  weights: [1]
  size: [15, 40]
  bold: 0.0

texture:
  prob: 0.5
  args:
    paths: [resources/image]
    weights: [1]
    alpha: [0, 1]
    grayscale: 0
    crop: 0.9

colormap2:
  paths: [resources/colormap/colormap2.txt]
  weights: [1]
  k: 2
  alpha: [1, 1]
  colorize: 1

colormap3:
  paths: [resources/colormap/colormap2.txt]
  weights: [1]
  k: 3
  alpha: [1, 1]
  colorize: 1

color:
  gray: [0, 255]
  alpha: [1, 1]
  colorize: 1

text_color:
  prob: 1
  args:
    weights: [1, 1]
    args:
      - rgb: [[180,255], [0,40], [0,40]]
        alpha: [1,1]
        grayscale: 0

      - rgb: [[0,20], [0,10], [0,10]]
        alpha: [1,1]
        grayscale: 0

background_color:
  rgb: [[180,250], [180,250], [180,250]]
  alpha: [1,1]
  grayscale: 0

shape:
  prob: 0.
  args:
    weights: [1, 0]
    args:
      # elastic distortion
      - alpha: [15, 30]
        sigma: [4, 12]
      # elastic distortion
      - alpha: [0, 2]
        sigma: [0, 0.6]

layout:
  weights: [1, 0]
  args:
    # flow layout
    - space: [-2, 5]
      line_align: [middle]
    # curve layout
    - curve: [20, 40]
      space: [-2, 5]
      convex: 0.05
      upward: 0.95

style:
  prob: 0.05
  args:
    weights: [1, 1, 0]
    args:
      # text border
      - size: [1, 12]
        alpha: [1, 1]
        grayscale: 0
      # text shadow
      - distance: [1, 2]
        angle: [0, 360]
        alpha: [0.3, 0.7]
        grayscale: 0
      # text extrusion
      - length: [1, 12]
        angle: [0, 360]
        alpha: [1, 1]
        grayscale: 0

transform:
  prob: 1.
  args:
    weights: [1,1,1,1,1,1,1]
    args:
      # perspective x
      - percents: [[0.5, 1], [1, 1]]
        aligns: [[0, 0], [0, 0]]
      # perspective y
      - percents: [[1, 1], [0.5, 1]]
        aligns: [[0, 0], [0, 0]]
      # trapezoidate x
      - weights: [1, 0, 1, 0]
        percent: [0.5, 1]
        align: [-1, 1]
      # trapezoidate y
      - weights: [0, 1, 0, 1]
        percent: [0.5, 1]
        align: [-1, 1]
      # skew x
      - weights: [1, 0]
        angle: [10, 20]
        ccw: 0.5
      # skew y
      - weights: [0, 1]
        angle: [10, 20]
        ccw: 0.5
      # rotate
      - angle: [10, 45]
        ccw: 0.5

pad:
  prob: 1
  args:
    pxs: [[0, 10], [0, 10], [0, 10], [0, 10]]

postprocess:
  args:
    # gaussian noise
    - prob: 0.
      args:
        scale: [1, 2]
        per_channel: 0
    # gaussian blur
    - prob: 0.
      args:
        sigma: [0, 1]
    # resample
    - prob: 0.
      args:
        size: [0.4, 0.4]
    # median blur
    - prob: 0.
      args:
        k: [1, 1]
